# Generated by Django 5.1 on 2025-05-15 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexense_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gptpackage',
            name='include_company_info',
            field=models.BooleanField(default=False, help_text="GPT'ye firma bilgilerini ekle"),
        ),
        migrations.AddField(
            model_name='gptpackage',
            name='include_personal_info',
            field=models.BooleanField(default=False, help_text="GPT'ye kişisel bilgileri ekle"),
        ),
        migrations.CreateModel(
            name='GptPackageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='gpt_package_files/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gpt_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hexense_core.gptpackage')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_gpt_package_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gpt Package File',
                'verbose_name_plural': 'Agent Management: Gpt Package Files',
            },
        ),
    ]
