# Generated by Django 5.1 on 2025-05-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexense_core', '0002_gptpackage_include_company_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptmodel',
            name='capabilities',
            field=models.JSONField(blank=True, default=list, help_text="['text', 'image', 'audio', 'code']"),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='context_window',
            field=models.IntegerField(blank=True, help_text='Maksimum bağlam penceresi (token)', null=True),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='input_types',
            field=models.JSONField(blank=True, default=list, help_text="Desteklenen input türleri: ['text', 'image', 'file_upload', 'url', 'audio', 'video', 'pdf', 'table']"),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='model_family',
            field=models.CharField(blank=True, help_text='GPT-4, Claude 3, Gemini 2.5 gibi', max_length=50),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='optimized_for',
            field=models.JSONField(blank=True, default=list, help_text="['general', 'code', 'reasoning', 'speed', 'cost']"),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='output_types',
            field=models.JSONField(blank=True, default=list, help_text="Beklenen çıktı türleri: ['text', 'image', 'json', 'table', 'audio']"),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='pricing_per_1k',
            field=models.JSONField(blank=True, default=dict, help_text='{"input": 0.01, "output": 0.03} (USD per 1K tokens)'),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='supports_function_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='supports_multimodal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gptmodel',
            name='supports_tool_use',
            field=models.BooleanField(default=False),
        ),
    ]
