# Generated by Django 5.1 on 2025-05-16 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexense_core', '0003_gptmodel_capabilities_gptmodel_context_window_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='hexense_core.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Bu profil kullanıcının aktif profili mi?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
