# Generated by Django 5.1 on 2025-05-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hexense_core', '0005_auto_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
    ]
