# Generated by Django 5.1 on 2025-05-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexense_core', '0006_remove_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_admin',
            field=models.BooleanField(default=False, help_text='Firma bilgilerini ve kullanıcıları yönetme yetkisi'),
        ),
    ]
