# Generated by Django 5.1 on 2025-05-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexense_core', '0008_remove_conversation_memory_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gptservice',
            name='input_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Beklenen parametreler ve açıklamaları'),
        ),
    ]
