# Generated by Django 5.1 on 2025-05-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexense_core', '0009_alter_gptservice_input_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='topic_embedding',
        ),
        migrations.AddField(
            model_name='conversation',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=10),
        ),
    ]
